steps:
  - name: node:12.3.1
    entrypoint: npm
    args: ["install"]
  - name: node:12.3.1
    entrypoint: npm
    args: ["install", "firebase-tools"]
  - name: node:12.3.1
    entrypoint: npm
    args: ["build"]
  - name: "node:12.3.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]
